<?php

namespace App\Consts;

class PrefectureConst
{
    public const PREFECTURES = [
        "hokkaido",
        "aomori",
        "iwate",
        "miyagi",
        "akita",
        "yamagata",
        "fukushima",
        "ibaraki",
        "tochigi",
        "gunma",
        "saitama",
        "chiba",
        "tokyo",
        "kanagawa",
        "niigata",
        "toyama",
        "ishikawa",
        "fukui",
        "yamanashi",
        "nagano",
        "gifu",
        "shizuoka",
        "aichi",
        "mie",
        "shiga",
        "kyoto",
        "osaka",
        "hyogo",
        "nara",
        "wakayama",
        "tottori",
        "shimane",
        "okayama",
        "hiroshima",
        "yamaguchi",
        "tokushima",
        "kagawa",
        "ehime",
        "kochi",
        "fukuoka",
        "saga",
        "nagasaki",
        "kumamoto",
        "oita",
        "miyazaki",
        "kagoshima",
        "okinawa"
    ];

    public const PREFECTURES_UPPER_CASE = [
        self::PREFECTURES[0]  => "Hokkaido",
        self::PREFECTURES[1]  => "Aomori",
        self::PREFECTURES[2]  => "Iwate",
        self::PREFECTURES[3]  => "Miyagi",
        self::PREFECTURES[4]  => "Akita",
        self::PREFECTURES[5]  => "Yamagata",
        self::PREFECTURES[6]  => "Fukushima",
        self::PREFECTURES[7]  => "Ibaraki",
        self::PREFECTURES[8]  => "Tochigi",
        self::PREFECTURES[9]  => "Gunma",
        self::PREFECTURES[10] => "Saitama",
        self::PREFECTURES[11] => "Chiba",
        self::PREFECTURES[12] => "Tokyo",
        self::PREFECTURES[13] => "Kanagawa",
        self::PREFECTURES[14] => "Niigata",
        self::PREFECTURES[15] => "Toyama",
        self::PREFECTURES[16] => "Ishikawa",
        self::PREFECTURES[17] => "Fukui",
        self::PREFECTURES[18] => "Yamanashi",
        self::PREFECTURES[19] => "Nagano",
        self::PREFECTURES[20] => "Gifu",
        self::PREFECTURES[21] => "Shizuoka",
        self::PREFECTURES[22] => "Aichi",
        self::PREFECTURES[23] => "Mie",
        self::PREFECTURES[24] => "Shiga",
        self::PREFECTURES[25] => "Kyoto",
        self::PREFECTURES[26] => "Osaka",
        self::PREFECTURES[27] => "Hyogo",
        self::PREFECTURES[28] => "Nara",
        self::PREFECTURES[29] => "Wakayama",
        self::PREFECTURES[30] => "Tottori",
        self::PREFECTURES[31] => "Shimane",
        self::PREFECTURES[32] => "Okayama",
        self::PREFECTURES[33] => "Hiroshima",
        self::PREFECTURES[34] => "Yamaguchi",
        self::PREFECTURES[35] => "Tokushima",
        self::PREFECTURES[36] => "Kagawa",
        self::PREFECTURES[37] => "Ehime",
        self::PREFECTURES[38] => "Kochi",
        self::PREFECTURES[39] => "Fukuoka",
        self::PREFECTURES[40] => "Saga",
        self::PREFECTURES[41] => "Nagasaki",
        self::PREFECTURES[42] => "Kumamoto",
        self::PREFECTURES[43] => "Oita",
        self::PREFECTURES[44] => "Miyazaki",
        self::PREFECTURES[45] => "Kagoshima",
        self::PREFECTURES[46] => "Okinawa"
    ];

    public const PREFECTURES_KANJI = [
        self::PREFECTURES[0]  => "北海",
        self::PREFECTURES[1]  => "青森",
        self::PREFECTURES[2]  => "岩手",
        self::PREFECTURES[3]  => "宮城",
        self::PREFECTURES[4]  => "秋田",
        self::PREFECTURES[5]  => "山形",
        self::PREFECTURES[6]  => "福島",
        self::PREFECTURES[7]  => "茨城",
        self::PREFECTURES[8]  => "栃木",
        self::PREFECTURES[9]  => "群馬",
        self::PREFECTURES[10] => "埼玉",
        self::PREFECTURES[11] => "千葉",
        self::PREFECTURES[12] => "東京",
        self::PREFECTURES[13] => "神奈川",
        self::PREFECTURES[14] => "新潟",
        self::PREFECTURES[15] => "富山",
        self::PREFECTURES[16] => "石川",
        self::PREFECTURES[17] => "福井",
        self::PREFECTURES[18] => "山梨",
        self::PREFECTURES[19] => "長野",
        self::PREFECTURES[20] => "岐阜",
        self::PREFECTURES[21] => "静岡",
        self::PREFECTURES[22] => "愛知",
        self::PREFECTURES[23] => "三重",
        self::PREFECTURES[24] => "滋賀",
        self::PREFECTURES[25] => "京都",
        self::PREFECTURES[26] => "大阪",
        self::PREFECTURES[27] => "兵庫",
        self::PREFECTURES[28] => "奈良",
        self::PREFECTURES[29] => "和歌山",
        self::PREFECTURES[30] => "鳥取",
        self::PREFECTURES[31] => "島根",
        self::PREFECTURES[32] => "岡山",
        self::PREFECTURES[33] => "広島",
        self::PREFECTURES[34] => "山口",
        self::PREFECTURES[35] => "徳島",
        self::PREFECTURES[36] => "香川",
        self::PREFECTURES[37] => "愛媛",
        self::PREFECTURES[38] => "高知",
        self::PREFECTURES[39] => "福岡",
        self::PREFECTURES[40] => "佐賀",
        self::PREFECTURES[41] => "長崎",
        self::PREFECTURES[42] => "熊本",
        self::PREFECTURES[43] => "大分",
        self::PREFECTURES[44] => "宮崎",
        self::PREFECTURES[45] => "鹿児島",
        self::PREFECTURES[46] => "沖縄"
    ];

    public const PREFECTURES_FULL_KANJI = [
        self::PREFECTURES[0]  => "北海道",
        self::PREFECTURES[1]  => "青森県",
        self::PREFECTURES[2]  => "岩手県",
        self::PREFECTURES[3]  => "宮城県",
        self::PREFECTURES[4]  => "秋田県",
        self::PREFECTURES[5]  => "山形県",
        self::PREFECTURES[6]  => "福島県",
        self::PREFECTURES[7]  => "茨城県",
        self::PREFECTURES[8]  => "栃木県",
        self::PREFECTURES[9]  => "群馬県",
        self::PREFECTURES[10] => "埼玉県",
        self::PREFECTURES[11] => "千葉県",
        self::PREFECTURES[12] => "東京都",
        self::PREFECTURES[13] => "神奈川県",
        self::PREFECTURES[14] => "新潟県",
        self::PREFECTURES[15] => "富山県",
        self::PREFECTURES[16] => "石川県",
        self::PREFECTURES[17] => "福井県",
        self::PREFECTURES[18] => "山梨県",
        self::PREFECTURES[19] => "長野県",
        self::PREFECTURES[20] => "岐阜県",
        self::PREFECTURES[21] => "静岡県",
        self::PREFECTURES[22] => "愛知県",
        self::PREFECTURES[23] => "三重県",
        self::PREFECTURES[24] => "滋賀県",
        self::PREFECTURES[25] => "京都府",
        self::PREFECTURES[26] => "大阪府",
        self::PREFECTURES[27] => "兵庫県",
        self::PREFECTURES[28] => "奈良県",
        self::PREFECTURES[29] => "和歌山県",
        self::PREFECTURES[30] => "鳥取県",
        self::PREFECTURES[31] => "島根県",
        self::PREFECTURES[32] => "岡山県",
        self::PREFECTURES[33] => "広島県",
        self::PREFECTURES[34] => "山口県",
        self::PREFECTURES[35] => "徳島県",
        self::PREFECTURES[36] => "香川県",
        self::PREFECTURES[37] => "愛媛県",
        self::PREFECTURES[38] => "高知県",
        self::PREFECTURES[39] => "福岡県",
        self::PREFECTURES[40] => "佐賀県",
        self::PREFECTURES[41] => "長崎県",
        self::PREFECTURES[42] => "熊本県",
        self::PREFECTURES[43] => "大分県",
        self::PREFECTURES[44] => "宮崎県",
        self::PREFECTURES[45] => "鹿児島県",
        self::PREFECTURES[46] => "沖縄県"
    ];
}
